Merge migrations as there were conflicts
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph:
(0064_alter_advice_type, 0064_update_teams_on_advice in cases).